#!/bin/sh
#
# cluster_viewer This shell script takes care of starting and stopping
#                the cluster viewer
# It is setup to run a staged Play application (play clean compile stage)
# and can be used to run the cluster viewer as a service in a Debian
# style environment (Debian, Ubuntu, Linux Mint etc.)
NAME=cluster_viewer
CMONKEY_HOME=/home/weiju/Projects/python/cmonkey-python
CLUSTER_VIEWER_HOME=$CMONKEY_HOME/cluster_viewer
PIDFILE=$CLUSTER_VIEWER_HOME/RUNNING_PID
DAEMON=$CLUSTER_VIEWER_HOME/target/start


# Do preliminary checks here, if any

# Handle manual control parameters like start, stop, status, restart, etc.

case "$1" in
    start)
        echo -n "Starting daemon: "$NAME
        start-stop-daemon --start --background --chdir $CLUSTER_VIEWER_HOME --pidfile $PIDFILE --exec $DAEMON
        echo "."
        ;;
    stop)
        echo -n "Stopping daemon: "$NAME
        start-stop-daemon --stop --chdir $CLUSTER_VIEWER_HOME --pidfile $PIDFILE
        echo "."
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
