#!/bin/sh
set -e
case "$1" in
    configure)
    ln -s /usr/share/pyshared/cmonkey /usr/lib/python2.7/dist-packages/
    ln -s /var/cmonkey-python /etc/
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    rm -f /usr/lib/python2.7/dist-packages/cmonkey
    rm -f /etc/cmonkey-python
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0
