library('RSQLite')

# Helper functionality to work with cMonkey/Python data in R
# This function reads cluster information from a SQLite database
# file generated by cMonkey-Python
#
# Explanation of the clusterStack object
# --------------------------------------
# clusterStack is a list containing |num clusters| elements
# Each element of this list is a list of
# 
# 1. $nrows: number of rows in cluster
# 2. $ncols: number of columns in cluster
# 3. $rows: row names in the cluster
# 4. $cols: column names in the cluster
# 5. $k: cluster number
# 6. $p.clust p value of motif scoring
#      vector of number, s elements, each element named like sequence type
# 7. $e.val e value of motif scoring
#      2xs matrix dimensions column name sequence type
#      s number of sequence types, columns named
# 8. $resid cluster residual
#      vector of number, 1 element, named 'ratios'
#
read.cmonkey.sqlite <- function(db.filename, iteration=0) {
  sqlite <- dbDriver("SQLite")
  con <- dbConnect(sqlite, dbname=db.filename)
  run.info <- dbGetQuery(con, "select last_iteration, num_clusters from run_infos")[1,]
  row.names <- dbGetQuery(con, "select name from row_names order by order_num")[,]
  col.names <- dbGetQuery(con, "select name from column_names order by order_num")[,]
  num.clusters <- run.info[,2]
  last.iteration <- run.info[,1]
  if (iteration == 0) iteration = last.iteration
  cat('# clusters:', num.clusters, '\n')
  cat('using iteration:', iteration, '\n')
  result <- list()

  cat('Reading cluster information...\n')
  for (cluster in 1:num.clusters) {
    cat('cluster', cluster, '\n')
    cluster.data <- list()
    row.members <- dbGetPreparedQuery(con, "select order_num from row_members where iteration = :iteration and cluster = :cluster",
                                      data.frame(iteration=iteration, cluster=cluster))[,]
    col.members <- dbGetPreparedQuery(con, "select order_num from column_members where iteration = :iteration and cluster = :cluster",
                                      data.frame(iteration=iteration, cluster=cluster))[,]
    cluster.residual <- dbGetPreparedQuery(con, "select residual from cluster_residuals where iteration = :iteration and cluster = :cluster",
                                      data.frame(iteration=iteration, cluster=cluster))[1,]

    # indexes in the database are 0-based, correct by 1 to use R indexing
    row.members <- row.members + 1
    col.members <- col.members + 1

    cluster.data$nrows <- length(row.members)
    cluster.data$ncols <- length(col.members)
    cluster.data$rows <- row.names[row.members]
    cluster.data$cols <- col.names[col.members]
    cluster.data$k <- cluster
    cluster.data$p.clust <- NULL
    cluster.data$e.val <- NULL
    cluster.data$resid <- cluster.residual
    result[[cluster]] <- cluster.data
  }
  cat('done.\n')
  dbDisconnect(con)
  result
}

args <- commandArgs(trailingOnly=TRUE)
if (length(args) > 0) {
  result.dir <- args[1]
  #ratio.filename <- args[1]
  #result.filename <- args[2]
  ratio.filename <- paste(result.dir, 'ratios.tsv.gz', sep='/')
  result.filename <- paste(result.dir, 'cmonkey_run.db', sep='/')

  ratios <- read.table(gzfile(ratio.filename), header=T, as.is=T, row.names=1)
  clusterStack <- read.cmonkey.sqlite(result.filename, 2001)
  print("Writing objects to R file...")
  save(ratios, clusterStack, file='output.RData')
  print("Done.")
} else {
  print("Usage: convert <output-dir>")
  print(args)
}
